### ISSUE TITLE
Streaming Switch 

### ISSUE THREAD

**Issue by Needletalk** [FaBjE/HiBy-Theme-MaterialDesign#1]
The toggle to switch between Tidal to Qobuz and viceversa don't work.

**Comment by FaBjE** [comment]
Does it work when you use the default skin?

I don't have either account so I can't test unfortunately.

**Comment by Needletalk** [comment]
Yes, with the default skin it works fine 
But using Material Design 
When I pressed and hold the tidal icon the list appears but I can't switch between services

**Comment by FaBjE** [comment]
Which firmware is your player on?
I tested it on my R3 Pro and it seems to work. But I'm still on FW1.6

**Comment by Needletalk** [comment]
I'm on firmware 2.0, also the radio shortcut doesn't work in this version

**Comment by FaBjE** [comment]
HiBy probably changed some reference names in the theme/firmware.
I need to reverse-engineer them from the firmware and take a good look.

I will need to find some time to do this, but I will get around to it eventually.
In the meantime, please post anything you find that doesn't work with the new version anymore.

**Comment by Needletalk** [comment]
Yes, it seems that the change some things, I'll check if there anything else that doesn't work. Thanks
Great job by the way, I love the theme.

**Comment by FaBjE** [comment]
I found some time to investigate and there were indeed some changes to the firmware that broke my theme.
I updated my theme and this should fix the issue. Could you test  the [new version ](https://github.com/FaBjE/HiBy-Theme-MaterialDesign/blob/master_PlayerFirmware_2.0/Builds/R3PRO/MaterialDesign.t?raw=true)and report back?

If it fixes things I will release it.

**Comment by Needletalk** [comment]
Of course,  I will report back my experience.

**Comment by Needletalk** [comment]
After some testing I have great results with the new version, the radio tab is lost but everything else works great. The switch between streaming services works. And the theme delivers a much better experience. Thanks a lot

**Comment by FaBjE** [comment]
Thanks for the update! I will release this version.

I had to remove the radio tab as my "hack" was no longer supported by this firmware. (will put that in the changelog)
