### ISSUE TITLE
Song progress bar too big and out of screen?

### ISSUE THREAD

**Issue by pepelugil** [FaBjE/HiBy-Theme-MaterialDesign#2]
Hello,

Progress bar seems to be too big and gets out of the screen, so when a song stars the position icon cannot be seen until some seconds has gone by (the much longer the song, the worst is the problem). At the end of the song something similar happens but it's not as steep.
This makes difficult go to the beginning of a song using the progress bar.

(Thanks for your great work your theme has really improved my Hiby R3 Pro Saber)

![start](https://user-images.githubusercontent.com/62351186/211921449-8a58dafa-bb6a-4bf8-9236-927d8e88bedf.jpg)

![mid](https://user-images.githubusercontent.com/62351186/211921475-a5f4f079-ba24-41d7-b3b1-63c881494420.jpg)

![end](https://user-images.githubusercontent.com/62351186/211921487-68de81cd-c3db-4b18-8e2d-b5746781c192.jpg)

**Comment by FaBjE** [comment]
Hi,

Thanks for the report. I checked on my player and I can reproduce the issue as well.
I will try to fix it shortly

**Comment by FaBjE** [comment]
Fixed in latest release.
Please let me know if it working for you.

**Comment by pepelugil** [comment]
Hi,
Tested your last release and now in my player is also working.
Thanks again for your great work!!
