### ISSUE TITLE
Side Menu

### ISSUE THREAD

**Issue by Needletalk** [FaBjE/HiBy-Theme-MaterialDesign#3]
Found a navegation/layout issue, When you select the artist tab on the Local Music Module and you bring the side Menu, this doesn't show up all the way, and the top part gets covered by the selection bar at the top. Also the about icon get cut a little at the bottom of the screen.

**Comment by FaBjE** [comment]
Thanks for the report. I fixed it in the latest release.
Could you check on your player if it is working ok now?

**Comment by Needletalk** [comment]
Hi, I check it and it worked. Problem Solved, thanks.
