### ISSUE TITLE
Artist name overlaps music sound quality text

### ISSUE THREAD

**Issue by pepelugil** [FaBjE/HiBy-Theme-MaterialDesign#4]
Hello,

When artist name is too long it overlaps music sound quality text, could you please check it?

Thanks

**Comment by FaBjE** [comment]
Could you describe the screen where this occurs?
Preferably post a picture?

**Comment by pepelugil** [comment]
Yes, sorry, it's in the main "Now Playing" screen, under the battery indicator:

![IMG_20230207_122851](https://user-images.githubusercontent.com/62351186/217237021-0acca3ad-0e17-4380-9634-bced6432a694.jpg)

**Comment by FaBjE** [comment]
Can you check if latest release fixes this issue?
https://github.com/FaBjE/HiBy-Theme-MaterialDesign/releases/download/PlayerFirmware_2.0_V4/MaterialDesign.t

**Comment by pepelugil** [comment]
Great now it's fine... you've also added scroll to artist text, great work!!

Lots of thanks
