### ISSUE TITLE
Folder view displays incorrect folder names at times and random gaps between folders randomly appear. 

### ISSUE THREAD

**Issue by ghost** [FaBjE/HiBy-Theme-MaterialDesign#5]
I started to look at folder view and I started noticing random gaps in folders. Also, some folder names (of album) did change or did not reflect the folder name (of album of new artist) another folder I was previously in.

**Comment by ghost** [comment]
![20230326_211625](https://user-images.githubusercontent.com/128943294/227840213-6614db09-67ed-49f9-8385-5e4fcbef22b5.jpg)

**Comment by ghost** [comment]
To clarify on the random incorrect folder names apart to occur when I click on a new folder. For example, I have my music organized in artist -> album -> individual songs folder structure and sometimes when I click out of an artist folder, and click on another artist there is a weird delay where the album folders displayed are of the previous artist I was viewing and the not the artist I am currently viewing. So in essence, there is an glitch/delay with incorrect folder names when opening a new artist folder. My overall sd card music structure is that at root directory I have music folder and a theme folder, then under music folder all the artists folders are displayed. Then once I click on an artist folder all the album folders (or albums) of this particular artist is displayed. Finally, I click on the album folder of interest to either listen to either album or individual song. I used Musicbee to organize my music with the following rules: "D:\Music to Hiby R3\<Album Artist>\<Album>\<Track #:2>. <Title>". Hopefully this helps, I wonder if the different image of the folders may be the culprit for the delay or incorrect folder displayed at times. I will try to get this issue on video and share it on github. 

This isn't to criticize your custom theme, I actually really enjoyed using the theme because of text scrolling and I have shared it on a headfi post because its really amazing. I only wanted to let you know of an issue I have found after another person on headfi mentioned a weird glitch on headfi. 

Link to their concern: https://www.head-fi.org/threads/hiby-r3-pro-portable-bluetooth-dap.916299/post-17479847

**Comment by DasRorikDude** [comment]
Found out that the folders that are getting their names replaced have special characters.

But the "new name" do not always have special characters.

**Comment by ghost** [comment]
Or can you include a modification where the folder view is return to its original state because I have never had an issues with folder view in the Hiby os. Also, is it possible to add a scroll wheel on the right side with the alphabet since I have all my music organized in artist and I have a decent amount of artist in my folders. It would allow scrolling to be more convenient.

**Comment by FaBjE** [comment]
Thanks for reporting the issue. I'm gonna need to find some time to properly look at this.
I checked real quick, but I can not replicate this issue at my device which makes it a bit harder to track down.

Given your picture, what device/firmware type do you have? My R3 Pro looks different.

Thanks for advertising my theme :) I do see this as constructive feedback, so no offense taken.

You could help me with debugging this by making a "no changes version" yourself. The theme file is just a zip file.
This is the file involved for the "folder view" https://github.com/FaBjE/HiBy-Theme-MaterialDesign/commits/master_PlayerFirmware_2.0/GUI%20Simulator/data/res/R3PRO/layout/theme2/listview/vg_listview_main_explorer.listview
It defines the contents for one folder in the list. You can click the button at the right with the "View at this point in history"
I suggest you start with: [this one](https://github.com/FaBjE/HiBy-Theme-MaterialDesign/blob/cbcb92165ae95bc934d44727938176022b0e7adc/GUI%20Simulator/data/res/R3PRO/layout/theme2/listview/vg_listview_main_explorer.listview) which is the unmodified firmware 2.0 version.
If you replace the file (with the same name/location) in the theme (zip) file (and put it on your device) you are good to go.

Unfortunately I can't add things like scrollbars in the theme, that is all defined by the firmware itself.

**Comment by ghost** [comment]
> Given your picture, what device/firmware type do you have? My R3 Pro looks different.


I'm running an custom firmware of 2.2 that expands library past 20,000 tracks. I reinstalled 2.2 original firmware today and I didn't experience any issues with folder view so I suspect it has to do something with the custom firmware. The gaps only occurred a couple of times and if I scroll down and then up the gaps disappear. I think it wouldn't be necessary to modify the firmware since I really like the custom theme as is. Custom firmware link: https://github.com/SuperTaiyaki/hiby-firmware-tools/issues/1#issuecomment-1484035903 

 I will see if I can change the folder view that you mentioned above. Thank you again on your repost. Also, @DasRorikDude has a completely different issue from mind concerning folder names changing with special characters. I think their issue is more important to focus on at the moment since the custom firmware is causing the issue.

**Comment by FaBjE** [comment]
@HotelWifi08 
Sorry for my late reply. 
Thank you for investigating this further. Did you have any progress with the old versions of the theme files?
I will "mark" this "caused by the (custom) firmware" for now. But If I can make changes to the theme that fixes the issue and works on both stock firmware and custom firmware I'm willing to do so.
But I can't support another "branch" of this theme.

@DasRorikDude 
Sorry I missed your comment. But I think a similar cause in the firmware (not this theme) is causing these issues.
Hiby's firmware is known for not being the strongest on handling special characters.
